# Generated by Django 5.0.6 on 2024-06-08 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('rareza', models.CharField(max_length=2)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'carta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateField()),
            ],
            options={
                'db_table': 'deck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'tienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('nif', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'jugador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('nombre', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'torneo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'transaccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idfactura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Copia',
            fields=[
                ('cantidad', models.IntegerField()),
                ('carta', models.OneToOneField(db_column='carta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='producte.carta')),
            ],
            options={
                'db_table': 'copia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repetido',
            fields=[
                ('cantidad', models.IntegerField()),
                ('carta', models.OneToOneField(db_column='carta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='producte.carta')),
                ('propietario', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'repetido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendida',
            fields=[
                ('cantidad', models.IntegerField()),
                ('carta', models.OneToOneField(db_column='carta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='producte.carta')),
                ('vendedor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vendida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('cantidad', models.IntegerField()),
                ('tienda', models.OneToOneField(db_column='tienda', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='producte.tienda')),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('jugador', models.OneToOneField(db_column='jugador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='producte.jugador')),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('duelista1', models.OneToOneField(db_column='duelista1', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='producte.jugador')),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'partida',
                'managed': False,
            },
        ),
    ]
